/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./components/AppIcon.vue')['default']
    LockScreen: typeof import('./components/screens/LockScreen.vue')['default']
    PhoneContainer: typeof import('./components/PhoneContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBar: typeof import('./components/status-bar/StatusBar.vue')['default']
    StatusIcon: typeof import('./components/status-bar/StatusIcon.vue')['default']
  }
}
