/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/calls/': RouteRecordInfo<'/calls/', '/calls', Record<never, never>, Record<never, never>>,
    '/calls/[id]': RouteRecordInfo<'/calls/[id]', '/calls/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/calls/credits': RouteRecordInfo<'/calls/credits', '/calls/credits', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/jorb/': RouteRecordInfo<'/jorb/', '/jorb', Record<never, never>, Record<never, never>>,
    '/v2': RouteRecordInfo<'/v2', '/v2', Record<never, never>, Record<never, never>>,
  }
}
